azure_settings:
  service_name: "cloud service name"
  management_certificate_path: "path/to/cert.pem"
  subscription_id: "subscription-id"
  storage_account_name: "storage-account-name"
  storage_account_key: "storage_account_key"
  disk_container_name: "my_disks_container"
  async_timeout: 5000
  debug: "true"