azure_settings:
  client_id: AZURE-CLIENT-ID
  tenant_id: AZURE-TENANT-ID
  client_secret: AZURE-CLIENT-SECRET
  subscription_id: AZURE-SUB-ID
  storage_account_name: STORAGE-ACCOUNT-NAME
  storage_account_container: STORAGE-ACCOUNT-CONTAINER
  storage_account_key: STORAGE-ACCOUNT-KEY
  group_name: AZURE-RESOURCE-GROUP-NAME 
  location: AZURE-RESOURCE-GROUP-LOCAITON
  async_timeout: 5000
  debug: "true"